### PR TITLE
processor_strptime support precise timestamp

### PR DESCRIPTION
**Pull request by messixukejia**

### CODE REVIEW

**Review by yyuuttaaoo — APPROVED** [review]
Plugin does not support ms/us/ns if input is timestamp

**Review by Goclis — APPROVED** [review]
LGTM

**Review by EvanLjp — APPROVED** [review]
LGTM

**Comment by EvanLjp** [comment]
please add change log and generate the plugin doc

**Comment by messixukejia** [comment]
1

**Pull request merged**
